site_name: AML Docs
site_url: https://notes.qubalee.com/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    #- toc.integrate
    - toc.follow
    - navigation.top
    - navigation.top.sticky
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.path
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - search.suggest
    - search.highlight
    - search.share

  plugins:
    - search
    - tags:
       - tags_file : tags.md
    - blog



  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

nav:
  - Home: index.md
  - Sampe Preparation:
    - overview : sample_prep/sample_preparation.md
  - Data Acquisition:
    - overview: data_acquisition/data_acquisition.md
  - Data Processing:
    - overview: data_processing/data_processing.md
  - Applications:
    - overview: applications/applications.md
  - Tags: tags.md

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/qubalee
    - icon: fontawesome/brands/researchgate
      link: https://www.researchgate.net/profile/Abdullah-Alqubalee
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/qubalee
      

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2025 <a href="https://qubalee.github.io"  target="_blank" rel="noopener">Abdullah Alqubalee</a>
